Cactus: output actual path to config-info on failure
this needs to get the cofiguration name from env variables and
setup_confguration.pl provides this in the EXE variable as the name of
the executable

diff --git a/lib/make/configure b/lib/make/configure
--- a/lib/make/configure
+++ b/lib/make/configure
@@ -1057,7 +1057,7 @@ cross_compiling=$ac_cv_prog_cc_cross
 
 echo "$ac_t""$ac_cv_prog_cc_works" 1>&6
 if test $ac_cv_prog_cc_works = no; then
-  { echo "configure: error: installation or configuration problem: C compiler cannot create executables (see configs/<configname>/config-data/config.log for details)." 1>&2; exit 1; }
+  { echo "configure: error: installation or configuration problem: C compiler cannot create executables (see configs/${EXE#cactus_}/config-data/config.log for details)." 1>&2; exit 1; }
 fi
 
 CROSS_COMPILE=`echo $CROSS_COMPILE | tr '[:upper:]' '[:lower:]'`
@@ -1066,7 +1066,7 @@ echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-co
 echo "configure:1067: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&5
 echo "$ac_t""$ac_cv_prog_cc_cross" 1>&6
 if test $ac_cv_prog_cc_cross = yes -a "x$CROSS_COMPILE" != xyes; then
-  { echo "configure: error: Could not run executable generated by C compiler (see configs/<configname>/config-data/config.log for details). If this is a cross configuration please set CROSS_COMPILE=yes." 1>&2; exit 1; }
+  { echo "configure: error: Could not run executable generated by C compiler (see configs/${EXE#cactus_}/config-data/config.log for details). If this is a cross configuration please set CROSS_COMPILE=yes." 1>&2; exit 1; }
 fi
 cross_compiling=$ac_cv_prog_cc_cross
 
@@ -1168,7 +1168,7 @@ cross_compiling=$ac_cv_prog_cc_cross
 
 echo "$ac_t""$ac_cv_prog_cxx_works" 1>&6
 if test $ac_cv_prog_cxx_works = no; then
-  { echo "configure: error: installation or configuration problem: C++ compiler cannot create executables (see configs/<configname>/config-data/config.log for details)." 1>&2; exit 1; }
+  { echo "configure: error: installation or configuration problem: C++ compiler cannot create executables (see configs/${EXE#cactus_}/config-data/config.log for details)." 1>&2; exit 1; }
 fi
 echo $ac_n "checking whether the C++ compiler ($CXX $CXXFLAGS $LDFLAGS) is a cross-compiler""... $ac_c" 1>&6
 echo "configure:1175: checking whether the C++ compiler ($CXX $CXXFLAGS $LDFLAGS) is a cross-compiler" >&5
