Added MPI=<type> configuration option.
Current types are

CUSTOM
   - must define, either in the environment or on the command line
     MPI_LIBS
     MPI_LIB_DIRS
     MPI_INC_DIRS

NATIVE
   - use the 'native' MPI for the machine;  this must be checked for and setup
     in the known-architecture file.

MPICH
   - use MPICH.  This is controlled by
     MPICH_DIR     - the MPICH installation directory
                     will search a few places for this if not defined.
     MPICH_DEVICE  - the MPICH device
                     again will search.
     If MPICH_DEVICE=globus you must set GLOBUS_DIR.

LAM
   - use LAM.  This is controlled by
     LAM_DIR       - the LAM installation directory
                     will search a few places.

This should still be treated as experimental, but it works on my laptop for MPICH and LAM.

I've updated the known-architectures/irix file for this, plus fixed the IRIX IRIX64 problem
(I think), but haven't tested the change yet.

Have fun,

Tom


git-svn-id: https://svn.cactuscode.org/flesh/trunk@748 17b73243-c579-4c4c-a9d2-2d5706c11dac

diff --git a/lib/make/configure.in b/lib/make/configure.in
--- a/lib/make/configure.in
+++ b/lib/make/configure.in
@@ -72,6 +72,165 @@ AC_SUBST(LD)
 LD=$CXX
 fi
 
+dnl Has the user asked for MPI ?
+
+if test -n "$MPI" ; then
+
+echo "Configuring with MPI"
+
+AC_DEFINE(MPI)
+
+case "$MPI" in
+
+    CUSTOM)
+    # Allow the user to completely specify at the command line,
+    echo "Custom MPI selected"
+
+    MPI_LIBS="$MPI_LIBS" 
+    MPI_LIB_DIRS="$MPI_LIB_DIRS"
+    MPI_INC_DIRS="$MPI_INC_DIRS"
+
+   ;;
+
+    MPICH)
+
+    echo "MPICH selected"
+    # MPICH is pretty configerable itself
+    if test -z "$MPICH_DIR" ; then
+       echo "MPICH selected but no MPICH_DIR set... Checking some places"
+
+       DIR_FOUND=""
+       for MPICH_DIR in /usr /usr/local /usr/local/mpich /usr/local/packages/mpich /usr/local/apps/mpich  
+       do
+           echo $ac_n "Looking in $MPICH_DIR""...$ac_c" 1>&6
+           if test -r "$MPICH_DIR/include/mpe.h" ; then
+              echo "$ac_t""...Found" 1>&6
+              DIR_FOUND="yes"
+              break
+           fi
+           echo "$ac_t""No" 1>&6
+       done
+
+       if test -z "$DIR_FOUND" ; then
+           echo "Unable to locate the MPICH directory - please set MPICH_DIR"
+           exit 2
+       fi
+    fi
+
+    if test -x "$MPICH_DIR/bin/tarch" ; then
+      MPICH_ARCH=`$MPICH_DIR/bin/tarch`
+      echo "MPICH architecture is $MPICH_ARCH"
+    else
+      echo "Cannot execute $MPICH_DIR/bin/tarch"
+      exit 2
+    fi
+
+    if test -z "$MPICH_DEVICE" ; then
+       echo "MPICH selected but no MPICH_DEVICE set... Checking for one"
+
+       DIR_FOUND=""
+       for MPICH_DEVICE in ch_shmem ch_p4 globus  
+       do
+           echo $ac_n "Looking for $MPICH_DEVICE""...$ac_c" 1>&6
+           if test -d "$MPICH_DIR/build/$MPICH_ARCH/$MPICH_DEVICE" ; then
+              echo "$ac_t""...Found" 1>&6
+              DIR_FOUND="yes"
+              break
+           fi
+           echo "$ac_t""No" 1>&6
+       done
+
+       if test -z "$DIR_FOUND" ; then
+           echo "Unable to locate the MPICH device - please set MPICH_DEVICE"
+           exit 2
+       fi
+    fi
+
+    case "$MPICH_DEVICE" in
+      globus)
+       if test -z "$GLOBUS_DIR" ; then
+         echo "GLOBUS selected, but GLOBUS_DIR not set !"
+         exit 2
+       fi
+       MPICH_DEVICE_LIB_DIR="$GLOBUS_DIR"
+       MPICH_DEVICE_LIBS="globus_common globus_dc globus_duct_control \
+                          globus_duct_runtime globus_duroc_bootstrap globus_duroc_control\
+                          globus_duroc_runtime globus_gass_cache globus_gass_client \
+                          globus_gass_file globus_gass_server globus_gass_server_ez \
+                          globus_gram_client globus_gram_myjob globus_gss globus_gss_assist \
+                          globus_hbm_client globus_hbm_datacollector globus_mp globus_nexus \
+                          globus_rsl globus_utp lber ldap ldif netperf"
+       ;;
+      *)
+       MPICH_DEVICE_LIB_DIR=""
+       MPICH_DEVICE_LIBS=""
+       ;;
+    esac
+    if test -r "$MPICH_DIR/build/$MPICH_ARCH/$MPICH_DEVICE/lib/libmpi.a" ; then
+       MPICH_LIB=mpi
+    else
+       MPICH_LIB=mpich
+    fi
+
+    MPI_LIBS="$MPICH_LIB $MPICH_DEVICE_LIBS" 
+    MPI_LIB_DIRS="$MPICH_DEVICE_LIB_DIR $MPICH_DIR/build/$MPICH_ARCH/$MPICH_DEVICE/lib"
+    MPI_INC_DIRS="$MPICH_DIR/include $MPICH_DIR/build/$MPICH_ARCH/$MPICH_DEVICE/include"
+
+    ;;
+
+    LAM)
+    echo "LAM selected"
+
+    if test -z "$LAM_DIR" ; then
+       echo "LAM selected but no LAM_DIR set... Checking some places"
+
+       DIR_FOUND=""
+       for LAM_DIR in /usr /usr/local /usr/local/lam /usr/local/packages/lam /usr/local/apps/lam  
+       do
+           echo $ac_n "Looking in $LAM_DIR""...$ac_c" 1>&6
+           if test -r "$LAM_DIR/h/lam.h" ; then
+              echo "$ac_t""...Found" 1>&6
+              DIR_FOUND="yes"
+              break
+           fi
+           echo "$ac_t""No" 1>&6
+       done
+
+       if test -z "$DIR_FOUND" ; then
+           echo "Unable to locate the LAM directory - please set LAM_DIR"
+           exit 2
+       fi
+    fi
+  
+    MPI_LIBS="mpi tstdio args t trillium " 
+    MPI_LIB_DIRS="$LAM_DIR/lib"
+    MPI_INC_DIRS="$LAM_DIR/h"
+
+    ;;
+
+    NATIVE)
+
+    echo "Native MPI selected"
+    # This should be filled out by the know-architecture stuff.
+    MPI_LIBS="" 
+    MPI_LIB_DIRS=""
+    MPI_INC_DIRS=""
+    ;; 
+
+    *)
+    echo "MPI selected, but no known MPI method - what is $withval ?"
+    exit 2;
+    ;;
+
+esac
+
+fi
+
+AC_SUBST(MPI_LIBS)
+AC_SUBST(MPI_LIB_DIRS)
+AC_SUBST(MPI_INC_DIRS)
+
+
 # If this is a known architecture, setup any specific flags.
 # This has to be done here as flags given to the compiler may
 # change the things detected later.
@@ -252,24 +411,24 @@ fi
 # Define the default floating point and integer precisions
 case "x$REAL_PRECISION" in
     "x16")
-	AC_DEFINE_UNQUOTED(CCTK_REAL_PRECISION_16, 1) ;;
+	AC_DEFINE(CCTK_REAL_PRECISION_16) ;;
     "x8")
-	AC_DEFINE_UNQUOTED(CCTK_REAL_PRECISION_8, 1) ;;
+	AC_DEFINE(CCTK_REAL_PRECISION_8) ;;
     "x4")
-	AC_DEFINE_UNQUOTED(CCTK_REAL_PRECISION_4, 1) ;;
+	AC_DEFINE(CCTK_REAL_PRECISION_4) ;;
     *)
-	AC_DEFINE_UNQUOTED(CCTK_REAL_PRECISION_8, 1) ;;
+	AC_DEFINE(CCTK_REAL_PRECISION_8) ;;
 esac
 
 case "x$INTEGER_PRECISION" in
     "x8")
-	AC_DEFINE_UNQUOTED(CCTK_INTEGER_PRECISION_8, 1) ;;
+	AC_DEFINE(CCTK_INTEGER_PRECISION_8) ;;
     "x4")
-	AC_DEFINE_UNQUOTED(CCTK_INTEGER_PRECISION_4, 1) ;;
+	AC_DEFINE(CCTK_INTEGER_PRECISION_4) ;;
     "x2")
-	AC_DEFINE_UNQUOTED(CCTK_INTEGER_PRECISION_2, 1) ;;
+	AC_DEFINE(CCTK_INTEGER_PRECISION_2) ;;
     *)
-	AC_DEFINE_UNQUOTED(CCTK_INTEGER_PRECISION_4, 1) ;;
+	AC_DEFINE(CCTK_INTEGER_PRECISION_4) ;;
 esac
 
 # Define any code needed before the definition of a Fortran subroutine
