Cactus: add configure test for functional C++11 math

diff --git a/lib/make/configure.in b/lib/make/configure.in
--- a/lib/make/configure.in
+++ b/lib/make/configure.in
@@ -523,7 +523,7 @@ AC_HEADER_STDC
 
 CCTK_CHECK_C99
 if test "$cctk_cv_have_c99" = "no" ; then
-  echo "Cactus requires a C99 compiler -- check your C compiler and C compiler flags"
+  echo >&2 "Cactus requires a C99 compiler -- check your C compiler and C compiler flags"
   exit 1
 fi
 
@@ -1027,11 +1027,14 @@ CCTK_CXX_STATIC_ASSERT
 CCTK_CXX_AUTO_SPECIFIER
 CCTK_CXX_LAMBDA
 CCTK_CXX_RANGE_BASED_FOR
+CCTK_CXX_MATH
 
 if test "$cctk_cv_have_cxx_auto_specifier" = no -o \
         "$cctk_cv_have_cxx_lambda" = no -o \
-        "$cctk_cv_have_cxx_range_based_for" = no; then
-  echo "Cactus requires a C++11 compiler -- check your C++ compiler and C++ compiler flags"
+        "$cctk_cv_have_cxx_range_based_for" = no -o \
+        "$cctk_cv_have_cxx_math" = no ; then
+  echo >&2 "Cactus requires a C++11 compiler -- check your C++ compiler and C++ compiler flags"
+  echo >&2 "If using g++ at least version 6 is required, if using icpc use -gxx-name to use libstc++ from g++ at least version 6"
   exit 1
 fi
 
