Introduce a new configuration flag DISABLE_REAL16 which disables support for the datatype CCTK_REAL16.  This is necessary because Cactus only detects whether C supports this datatype, and then assumes that Fortran behaves the same.
git-svn-id: https://svn.cactuscode.org/flesh/trunk@4149 17b73243-c579-4c4c-a9d2-2d5706c11dac

diff --git a/lib/make/configure b/lib/make/configure
--- a/lib/make/configure
+++ b/lib/make/configure
@@ -4815,7 +4815,11 @@ case "x$ac_cv_sizeof_float" in
       CCTK_REAL4='float' ;;
 esac
 
-if test -n "$CCTK_REAL16" ; then
+if test "x$DISABLE_REAL16" != 'xyes' -a "x$DISABLE_REAL16" != 'xno' -a "x$DISABLE_REAL16" != 'x'; then
+    { echo "configure: error: Didn't recognise setting of DISABLE_REAL16=\"$DISABLE_REAL16\"; should be either \"yes\" or \"no\" or \"\" (empty)" 1>&2; exit 1; }
+fi
+
+if test -n "$CCTK_REAL16" -a "x$DISABLE_REAL16" != 'xyes' ; then
   cat >> confdefs.h <<EOF
 #define CCTK_REAL16 $CCTK_REAL16
 EOF
