Added determination of the size of a pointer.
Now have

#define POINTER integer*SIZEOF_CHAR_P

and

#define CCTK_STRING POINTER

in config.h .

Tom


git-svn-id: https://svn.cactuscode.org/flesh/trunk@112 17b73243-c579-4c4c-a9d2-2d5706c11dac

diff --git a/lib/make/configure b/lib/make/configure
--- a/lib/make/configure
+++ b/lib/make/configure
@@ -1489,6 +1489,45 @@ cat >> confdefs.h <<EOF
 EOF
 
 
+echo $ac_n "checking size of char *""... $ac_c" 1>&6
+echo "configure:1494: checking size of char *" >&5
+if eval "test \"`echo '$''{'ac_cv_sizeof_char_p'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test "$cross_compiling" = yes; then
+    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1502 "configure"
+#include "confdefs.h"
+#include <stdio.h>
+main()
+{
+  FILE *f=fopen("conftestval", "w");
+  if (!f) exit(1);
+  fprintf(f, "%d\n", sizeof(char *));
+  exit(0);
+}
+EOF
+if { (eval echo configure:1513: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+then
+  ac_cv_sizeof_char_p=`cat conftestval`
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  ac_cv_sizeof_char_p=0
+fi
+rm -fr conftest*
+fi
+
+fi
+echo "$ac_t""$ac_cv_sizeof_char_p" 1>&6
+cat >> confdefs.h <<EOF
+#define SIZEOF_CHAR_P $ac_cv_sizeof_char_p
+EOF
+
+
 
 
 ARFLAGS=rucs
