Cactus: don't refer to BSD_SOURCE for M_PI and strdup anymore
it is scheduled to go away

diff --git a/lib/make/configure b/lib/make/configure
--- a/lib/make/configure
+++ b/lib/make/configure
@@ -2226,7 +2226,7 @@ if eval "test \"`echo '$cctk_cv_defined_'$cctk_safe`\" = yes"; then
   :
 else
   echo "$ac_t""no" 1>&6
-{ echo "configure: error: M_PI not defined. Please add -D_BSD_SOURCE to CFLAGS." 1>&2; exit 1; }
+{ echo "configure: error: M_PI not defined. Try adding -D_XOPEN_SOURCE to CFLAGS." 1>&2; exit 1; }
 
 fi
 
@@ -2264,7 +2264,7 @@ if eval "test \"`echo '$cctk_cv_has_prototype_'$cctk_safe`\" = yes"; then
   :
 else
   echo "$ac_t""no" 1>&6
-{ echo "configure: error: strdup has no prototype. Please add -D_BSD_SOURCE to CFLAGS." 1>&2; exit 1; }
+{ echo "configure: error: strdup has no prototype. Try adding -D_XOPEN_SOURCE_EXTENDED to CFLAGS." 1>&2; exit 1; }
 
 fi
 
@@ -2310,7 +2310,7 @@ if eval "test \"`echo '$cctk_cv_has_prototype_'$cctk_safe`\" = yes"; then
   :
 else
   echo "$ac_t""no" 1>&6
-{ echo "configure: error: strdup has no prototype. Please add -D_BSD_SOURCE to CXXFLAGS." 1>&2; exit 1; }
+{ echo "configure: error: strdup has no prototype. Try adding -D_XOPEN_SOURCE_EXTENDED to CXXFLAGS." 1>&2; exit 1; }
 
 fi
 
@@ -8788,7 +8788,7 @@ cat > conftest.$ac_ext <<EOF
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
     builtin and then its argument prototype would still apply.  */
-char wo8th3;
+char NH40ZO;
 
 int main() {
 mkstemp()
