Patch from Barry Wardell, thanks:
Enables support for compiling HTML versions of
the Cactus documentation. It adds new build targets:

ReferenceManualHTML
MaintainersGuideHTML
UsersGuideHTML
*-ThornDocHTML
*-ArrangementDocHTML
ThornDocHTML
ArrangementDocHTML
ThornGuideHTML

Which are HTML equivalents of the existing doc targets. This makes use
of the small new scripts lib/sbin/ArrangementDocHTML and
lib/sbin/ThornDocHTML.

This patch also introduces a small new script, lib/sbin/ConvertFigures,
which automates the process of converting figures to the correct format for
htlatex.

Finally, it makes some changes to doc/latex/cactus.sty to improve the
rendering of the HTML. It also modifies the Reference Guide to produce a
more consistent result (any cases of the CCTKFunc macro were updated to
use the newer FunctionDescriptionEntry).


git-svn-id: https://svn.cactuscode.org/flesh/trunk@4621 17b73243-c579-4c4c-a9d2-2d5706c11dac

diff --git a/doc/ThornGuide/Makefile b/doc/ThornGuide/Makefile
--- a/doc/ThornGuide/Makefile
+++ b/doc/ThornGuide/Makefile
@@ -32,7 +32,7 @@ ifeq ($(strip $(MASTER_FILE)), )
 endif
 
 IMAGE_FILE=$(CCTK_HOME)/doc/UsersGuide/bincactus2.pdf
-
+IMAGE_FILE_HTML=$(CCTK_HOME)/doc/UsersGuide/bincactus2.ps
 
 -include make.thornlist
 
@@ -58,6 +58,28 @@ $(MASTER_FILE).pdf: $(MASTER_FILE).tex
 	   echo "  Cannot find $@, an error must have occured."; \
 	fi
 
+ThornGuideHTML: $(MASTER_FILE).tex
+	# Convert figures to postscript
+	$(CCTK_HOME)/lib/sbin/ConvertFigures $(CCTK_HOME)/arrangements
+	@echo "  LaTeXing $<...."
+	# Fall through any latex errors so as to print sensible error message
+	-htlatex $< "html,2,fn-in" "" "" --interaction=nonstopmode < /dev/null 2>&1 | tee LOG_LATEX_FULL_MSGS | grep -v Underfull | grep -v Overfull | grep -v OT1 > LOG_LATEX_MSGS
+	if test -e "ThornGuide.html"; then                                    \
+	   if grep "^\! " "LOG_LATEX_FULL_MSGS" | grep -v "destination with the same identifier" | grep -v "You have requested package" ; then            \
+	     echo "  Problem in $<.  See $(DOCBUILDDIR)/LOG_LATEX_* .";  \
+	     exit 1;                                             \
+	   elif grep "^LaTeX Warning:" "LOG_LATEX_FULL_MSGS" | grep -v "destination with the same identifier" | grep -v "You have requested package" ; then         \
+	     echo "  Warnings in $<.  See $(DOCBUILDDIR)/LOG_LATEX_* ."; \
+	     exit 0;                                             \
+	   fi;                                                   \
+	   mkdir -p $(CCTK_HOME)/doc/HTML/ThornGuide;            \
+	   cp ThornGuide*.png  $(CCTK_HOME)/doc/HTML/ThornGuide; \
+     cp ThornGuide*.html $(CCTK_HOME)/doc/HTML/ThornGuide; \
+     cp ThornGuide.css   $(CCTK_HOME)/doc/HTML/ThornGuide; \
+	else                                                     \
+	   echo "  Cannot find $@, an error must have occured."; \
+	fi
+
 $(MASTER_FILE).tex:  $(foreach thorn, $(THORN_DEPENDENCIES), $(thorn)/param.ccl $(thorn)/interface.ccl $(thorn)/schedule.ccl) $(THORNLIST)
 	@echo "  Gathering documentation from thorn ccl files"
 	@echo "    Processing...."
@@ -71,6 +93,9 @@ $(MASTER_FILE).tex:  $(foreach thorn, $(THORN_DEPENDENCIES), $(thorn)/param.ccl 
 	$(PERL) -s $(CCTK_HOME)/lib/sbin/ThornGuide.pl -cctk_home=$(CCTK_HOME) -directory=$(ARRANGEMENTS_DIR) -thornlist=$(THORNLIST) -outdir=./ -outfile=$(MASTER_FILE).tex -tocdepth=$(TOCDEPTH) > LOG_THORNGUIDE_MSGS 2>&1
 	if test -e $(IMAGE_FILE) && test ! -e "bincactus2.pdf"; then \
 	   cp $(IMAGE_FILE) .;                                       \
+	fi
+	if test -e $(IMAGE_FILE_HTML) && test ! -e "bincactus2.ps"; then \
+	   cp $(IMAGE_FILE_HTML) .;                                       \
 	fi
 
 make.thornlist: $(THORNLIST) 
