Added search for include/lam and lib/lam so can just do
MPI=LAM

when configuring on machines setup in that way (e.g. the rh6.2 rpm installation).

Tom


git-svn-id: https://svn.cactuscode.org/flesh/trunk@1942 17b73243-c579-4c4c-a9d2-2d5706c11dac

diff --git a/lib/make/extras/MPI/LAM b/lib/make/extras/MPI/LAM
--- a/lib/make/extras/MPI/LAM
+++ b/lib/make/extras/MPI/LAM
@@ -4,24 +4,35 @@
 #   @date      Wed Jul 21 13:27:07 1999
 #   @author    Tom Goodale
 #   @desc 
-#   
+#   Configure Cactus to compile with the LAM version of MPI.
 #   @enddesc
-#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/extras/MPI/LAM,v 1.3 2000-10-15 17:21:52 tradke Exp $ 
+#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/extras/MPI/LAM,v 1.4 2000-12-13 09:04:22 goodale Exp $ 
 # @@*/
 
 echo "LAM selected"
 
 if test -z "$LAM_LIB_DIR" -o -z "$LAM_INC_DIR" ; then
   if test -z "$LAM_DIR" ; then
-     echo "LAM selected but no LAM_DIR set... Checking some places"
-     CCTK_Search LAM_DIR "/usr /usr/local /usr/local/lam /usr/local/packages/lam /usr/local/apps/lam" h/lam.h
-     if test -z "$LAM_DIR" ; then
-       echo "Unable to locate the LAM directory - please set LAM_DIR"
-       exit 2
-     fi
+    echo "LAM selected but no LAM_DIR set... Checking some places"
+    if test -d "/usr/include/lam" -a -d "/usr/lib/lam" ; then
+      LAM_LIB_DIR="/usr/lib/lam"
+      LAM_INC_DIR="/usr/include/lam"
+    elif test -d "/usr/local/include/lam" -a -d "/usr/local/lib/lam" ; then
+      LAM_LIB_DIR="/usr/local/lib/lam"
+      LAM_INC_DIR="/usr/local/include/lam"
+    else
+      CCTK_Search LAM_DIR "/usr /usr/local /usr/local/lam /usr/local/packages/lam /usr/local/apps/lam" h/lam.h
+      if test -z "$LAM_DIR" ; then
+        echo "Unable to locate the LAM directory - please set LAM_DIR"
+        exit 2
+      fi
+    fi
   fi
-  LAM_LIB_DIR="$LAM_DIR/lib"
-  LAM_INC_DIR="$LAM_DIR/h"
+  : ${LAM_LIB_DIR="$LAM_DIR/lib"}
+  : ${LAM_INC_DIR="$LAM_DIR/h"}
+
+  echo "Using $LAM_LIB_DIR as lam library path"
+  echo "Using $LAM_INC_DIR as lam include path"
 fi
 
 MPI_LIBS="mpi tstdio args t trillium " 
