Added Myrinet and ch_gm.
Put MYRINET_DIR=... to tell it where to find the MYRINET stuff.

Tom


git-svn-id: https://svn.cactuscode.org/flesh/trunk@1005 17b73243-c579-4c4c-a9d2-2d5706c11dac

diff --git a/lib/make/extras/MPI/MPICH b/lib/make/extras/MPI/MPICH
--- a/lib/make/extras/MPI/MPICH
+++ b/lib/make/extras/MPI/MPICH
@@ -6,7 +6,7 @@
 #   @desc 
 #   
 #   @enddesc
-#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/extras/MPI/MPICH,v 1.3 1999-07-29 19:02:04 lanfer Exp $ 
+#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/extras/MPI/MPICH,v 1.4 1999-09-28 14:09:08 goodale Exp $ 
 # @@*/
 
 
@@ -38,7 +38,7 @@ fi
 
 if test -z "$MPICH_DEVICE" ; then
    echo "MPICH selected but no MPICH_DEVICE set... Checking for one"
-   CCTK_Search MPICH_DEVICE "ch_p4 ch_shmem globus" lib $MPICH_DIR/build/$MPICH_ARCH/$MPICH_DEVICE
+   CCTK_Search MPICH_DEVICE "ch_p4 ch_shmem globus ch_gm" lib $MPICH_DIR/build/$MPICH_ARCH/$MPICH_DEVICE
     if test -z "$MPICH_DEVICE" ; then
        echo "Unable to locate the MPICH device - please set MPICH_DEVICE"
        exit 2
@@ -51,7 +51,7 @@ fi
 case "$MPICH_DEVICE" in
   globus)
    if test -z "$GLOBUS_LIB_DIR" ; then
-     echo "GLOBUS selected, but GLOBUS_LIB_DIR not set !"
+      echo "GLOBUS selected, but GLOBUS_LIB_DIR not set !"
      exit 2
    fi
    MPICH_DEVICE_LIB_DIR="$GLOBUS_LIB_DIR"
@@ -66,7 +66,19 @@ case "$MPICH_DEVICE" in
       MPICH_DEVICE_LIBS="$MPICH_DEVICE_LIBS pthread"
    fi
    ;;
-  *)
+ ch_gm)
+   if test -z "$MYRINET_DIR" ; then
+      echo "Myrinet device selected but no MYRINET_DIR set... Checking some places"
+      CCTK_Search MYRINET_DIR "/usr /usr/local /usr/local/myrinet /usr/local/packages/myrinet /usr/local/apps/myrinet" lib/libgm.a
+      if test -z "$MYRINET_DIR" ; then
+         echo "Unable to locate the Myrinet directory - please set MYRINET_DIR"
+         exit 2
+      fi
+   fi
+   MPICH_DEVICE_LIB_DIR="$MYRINET_DIR/lib"
+   MPICH_DEVICE_LIBS="gm"
+   ;;
+ *)
    MPICH_DEVICE_LIB_DIR=""
    MPICH_DEVICE_LIBS=""
    ;;
@@ -85,4 +97,13 @@ fi
 MPI_LIBS="$MPICH_LIB $MPICH_DEVICE_LIBS" 
 MPI_LIB_DIRS="$MPICH_DEVICE_LIB_DIR $MPICH_DIR/build/$MPICH_ARCH/$MPICH_DEVICE/lib"
 MPI_INC_DIRS="$MPICH_DIR/include $MPICH_DIR/build/$MPICH_ARCH/$MPICH_DEVICE/include"
+
+
+
+
+
+
+
+
+
 
