Use the NATIVE_MPI_XXX variables from the known-archs stuff here to finally set the MPI libs, libdirs, and includedirs.
Also test if MPI=NATIVE was selected but the system doesn't provide a
native MPI.


git-svn-id: https://svn.cactuscode.org/flesh/trunk@1514 17b73243-c579-4c4c-a9d2-2d5706c11dac

diff --git a/lib/make/extras/MPI/NATIVE b/lib/make/extras/MPI/NATIVE
--- a/lib/make/extras/MPI/NATIVE
+++ b/lib/make/extras/MPI/NATIVE
@@ -6,13 +6,18 @@
 #   @desc 
 #   
 #   @enddesc
-#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/extras/MPI/NATIVE,v 1.2 1999-07-21 12:52:55 goodale Exp $ 
+#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/extras/MPI/NATIVE,v 1.3 2000-04-04 10:01:33 tradke Exp $ 
 # @@*/
 
 echo "Native MPI selected"
 
 # This should be filled out by the know-architecture stuff.
 
-: ${MPI_LIBS=""} 
-: ${MPI_LIB_DIRS=""}
-: ${MPI_INC_DIRS=""}
+if test -z "$NATIVE_MPI_LIBS" ; then
+  echo "ERROR: NATIVE MPI selected, but this architecture has no native MPI"
+  exit 2
+fi
+
+MPI_LIBS=$NATIVE_MPI_LIBS
+MPI_LIB_DIRS=${NATIVE_MPI_LIB_DIRS:-""}
+MPI_INC_DIRS=${NATIVE_MPI_INC_DIRS:-""}
