Changed the LIBDIRS setting slightly for Lahey, so that you can set the LAHEY installation directory (and thus overrid e Cactus looking in /usr/local/lf9555) using the LAHEY environment variable.
e.g.

gmake lahey-config LAHEY=wereitisonthismachine

Also reports if no directory was found


git-svn-id: https://svn.cactuscode.org/flesh/trunk@1779 17b73243-c579-4c4c-a9d2-2d5706c11dac

diff --git a/lib/make/known-architectures/linux b/lib/make/known-architectures/linux
--- a/lib/make/known-architectures/linux
+++ b/lib/make/known-architectures/linux
@@ -141,7 +141,18 @@ else
        : ${F77_OPTIMISE_FLAGS="-O"}
        : ${F90_OPTIMISE_FLAGS="-O"}         
        : ${LIBS="fj9i6 fj9e6 fj9f6"} 
-       : ${LIBDIRS='$(LAHEY)/lib /usr/local/lf9555/lib'} 
+       if test -n "$LAHEY" ; then
+         : ${LIBDIRS=$LAHEY}
+       else
+         if test -d '/usr/local/lf9555/lib' ; then
+	   : ${LIBDIRS="/usr/local/lf9555/lib"}
+         fi
+       fi
+       if test -z "${LIBDIRS}" ; then
+         echo "Unable to locate LAHEY installation directory"
+         echo "Please configure with LAHEY=... or set LAHEY in your environment"
+         exit 2
+       fi
        ;;
      SGI)
        : ${LIBS="fortran ffio m"} 
