Added in secondary cache info.  Under linux and irix it examines the machine on which the configuration is happening, so it may not be correct for other machines with the same architecture.  E.g. the aei origin has a 4Mb cache, but skuld only has a 1 Mb cache.
You should be able to override the detection on the configuration line
with something like L2_CACHELINE_BYTES=xxx L2_CACHE_SIZE=xxx

Tom


git-svn-id: https://svn.cactuscode.org/flesh/trunk@1386 17b73243-c579-4c4c-a9d2-2d5706c11dac

diff --git a/lib/make/known-architectures/linux b/lib/make/known-architectures/linux
--- a/lib/make/known-architectures/linux
+++ b/lib/make/known-architectures/linux
@@ -102,4 +102,24 @@ else
        ;;
   esac    
 
+# Cache stuff
+  if test -z "$L2_CACHELINE_BYTES" ; then
+    L2_CACHELINE_BYTES=32
+    echo "Setting L2_CACHELINE_BYTES to $L2_CACHELINE_BYTES"
+  fi
+
+  if test -z "$L2_CACHE_SIZE" ; then
+    L2_CACHE_SIZE="`cat /proc/cpuinfo | perl -nae 'print $F[3] if(m:cache:)'`*1024"
+    echo "Setting L2_CACHE_SIZE to $L2_CACHE_SIZE bytes"
+  fi
+
+# MPI stuff
+
+  if test -n "$MPI" ; then
+    if test "$MPI" = "NATIVE" ; then
+      echo "ERROR: NATIVE MPI selected, but linux has no native MPI"
+      exit 2
+    fi
+  fi
+
 fi
